<?php
// Acount Type For Wallet Maintain

$acount_type[1] = 1; // Referral Bonus Receive By Member OK
$acount_type[2] = 2; // Principle Return Receive By Member  
$acount_type[3] = 3; // Level ROI INCOME Receive By Member  
$acount_type[4] = 4; // ROI INCOME 
$acount_type[5] = 5; // Package Buy 
$acount_type[6] = 6; // Credit Fund For TOPUP FROM Wallet 
$acount_type[7] = 7; // Reserved Token Credit
$acount_type[8] = 8; // Trade Sale Amount
$acount_type[9] = 9; // Trade Buy
$acount_type[10] = 10; // Cancel Buy Trade
$acount_type[11] = 11; // Cancel Sale Trade
$acount_type[12] = 12; // Trade Level Income
$acount_type[13] = 13; // Share Holder Bonus
$acount_type[14] = 14; // Package Buy Trade Bonus ok last
$acount_type[15] = 15; // Withdrawal
$acount_type[16] = 16; // share transfer to tora
$acount_type[17] = 17; // Share Holder Bonus To sponser
$acount_type[18] = 18; // Amount Transfer To Main Wallet By Member
$acount_type[19] = 19; // Debit Fund From Admin To Member 
$acount_type[20] = 20; // Debit From E-Wallet For Topup To Member 
$acount_type[21] = 21; // Admin Fund Credit To Member 
$acount_type[22] = 22; // Debit Main Wallet 
$acount_type[23] = 23; // Debit E-Wallet For Transfer To Main Wallet By Member 
$acount_type[24] = 24; // Debit From E-Wallet For Upgrade To Member
$acount_type[25] = 25; // Commission-Wallet Transfer Tax
$acount_type[26] = 26; // Commission-Wallet Blocked
$acount_type[27] = 27; // E-Wallet Blocked
$acount_type[28] = 28; // Member Blocked
$acount_type[29] = 29; // To E-Wallet
$acount_type[30] = 30; // Wallet Withdrawal Revert
$acount_type[31] = 31; // 1 Month Rental Bonus Revert To
$acount_type[32] = 32; // Tora Share Buy
$acount_type[33] = 33; // Tora Share Credit
$acount_type[34] = 34; // Bonus On Tora Share Buy By Member
$acount_type[35] = 35; // Redeem gift voucher
$acount_type[36] = 36; // Lottery Link-Up Bonus
$acount_type[37] = 37; // Transfer SMG To Cash Wallet
$acount_type[38] = 38; // Credit Cash By SMG Wallet
$acount_type[39] = 39; // Debit From E-Wallet For Buy Ticket To Member When Any Ticket not buy in current week
$acount_type[40] = 40; // Cancel Buy Trade
$acount_type[41] = 41; // Cancel Withdrawal
$acount_type[42] = 42; // Company Wallet Transfer to
$acount_type[43] = 43; // Company Wallet Received from

$acount_type_desc[1] = "Referral Bonus";
$acount_type_desc[2] = "Principle Return";
$acount_type_desc[3] = "Level ROI Bonus";
$acount_type_desc[4] = "ROI Bonus";
$acount_type_desc[5] = "Activation";
$acount_type_desc[6] = "Deposit Fund"; //Debit Fund FROM Admin To
$acount_type_desc[7] = "Reserved Token Credit";
$acount_type_desc[8] = "Trade Sale";
$acount_type_desc[9] = "Trade Buy";
$acount_type_desc[10] = "Cancel Buy Trade";
$acount_type_desc[11] = "Cancel Sale Trade";
$acount_type_desc[12] = "Trade Level Income";
$acount_type_desc[13] = "Owner Holder Bonus";
$acount_type_desc[14] = "Package Buy Trade Bonus";
$acount_type_desc[15] = "Withdrawal";
$acount_type_desc[16] = "share transfer to tora";
$acount_type_desc[17] = "Share Holder Bonus";//ok
$acount_type_desc[18] = "Credit CASH Wallet For Transfer From SMG-Wallet By";
$acount_type_desc[19] = "Debit SMG-Wallet For Transfer To CASH Wallet By";//Debit E-Wallet For Transfer To Member
$acount_type_desc[20] = "Activation"; //Credit E-Wallet For Transfer By Member
$acount_type_desc[21] = "By Admin Cr";
$acount_type_desc[22] = "By Admin Dr";
$acount_type_desc[23] = "Debit E-Wallet For Transfer To Main Wallet By Member ";
$acount_type_desc[24] = "Upgrade";
$acount_type_desc[25] = "E-Wallet To Commission-Wallet Transfer Tax";//Reserve
$acount_type_desc[26] = "Commission-Wallet Blocked";
$acount_type_desc[27] = "E-Wallet Blocked";
$acount_type_desc[28] = "Member Blocked";
$acount_type_desc[29] = "To E-Wallet";
$acount_type_desc[30] = "Bank Withdrawal Revert To";
$acount_type_desc[31] = "1 Month Rental Bonus Revert To";
$acount_type_desc[32] = "Tora Share Buy";
$acount_type_desc[33] = "Tora Share Credit";
$acount_type_desc[34] = "Tora Share Buy"; //Bonus On 
$acount_type_desc[35] = "Redeem gift voucher"; 
$acount_type_desc[36] = "Lottery Link-Up Bonus";
$acount_type_desc[37] = "Credit SMG Wallet For Transfer From CASH-Wallet By";
$acount_type_desc[38] = "Debit CASH-Wallet For Transfer To SMG Wallet By";
$acount_type_desc[39] = "Cancel Buy Trade";
$acount_type_desc[40] = "Cancel Withdrawal";
$acount_type_desc[42] = "Company Wallet Transfer to";
$acount_type_desc[43] = "Company Wallet Received from";


$wallet_type[1] = "Main Wallet";//Commission Wallet(amount)
$wallet_type[2] = "E-Wallet"; // activationw(USD Deposit Wallet)(activationw)
?>