<?php
$country_list = array(
		"Afghanistan",
		"Albania",
		"Algeria",
		"Andorra",
		"Angola",
		"Antigua and Barbuda",
		"Argentina",
		"Armenia",
		"Australia",
		"Austria",
		"Azerbaijan",
		"Bahamas",
		"Bahrain",
		"Bangladesh",
		"Barbados",
		"Belarus",
		"Belgium",
		"Belize",
		"Benin",
		"Bhutan",
		"Bolivia",
		"Bosnia and Herzegovina",
		"Botswana",
		"Brazil",
		"Brunei",
		"Bulgaria",
		"Burkina Faso",
		"Burundi",
		"Cambodia",
		"Cameroon",
		"Canada",
		"Cape Verde",
		"Central African Republic",
		"Chad",
		"Chile",
		"China",
		"Colombi",
		"Comoros",
		"Congo (Brazzaville)",
		"Congo",
		"Costa Rica",
		"Cote d'Ivoire",
		"Croatia",
		"Cuba",
		"Cyprus",
		"Czech Republic",
		"Denmark",
		"Djibouti",
		"Dominica",
		"Dominican Republic",
		"East Timor (Timor Timur)",
		"Ecuador",
		"Egypt",
		"El Salvador",
		"Equatorial Guinea",
		"Eritrea",
		"Estonia",
		"Ethiopia",
		"Fiji",
		"Finland",
		"France",
		"Gabon",
		"Gambia, The",
		"Georgia",
		"Germany",
		"Ghana",
		"Greece",
		"Grenada",
		"Guatemala",
		"Guinea",
		"Guinea-Bissau",
		"Guyana",
		"Haiti",
		"Honduras",
		"Hungary",
		"Iceland",
		"India",
		"Indonesia",
		"Iran",
		"Iraq",
		"Ireland",
		"Israel",
		"Italy",
		"Jamaica",
		"Japan",
		"Jordan",
		"Kazakhstan",
		"Kenya",
		"Kiribati",
		"Korea, North",
		"Korea, South",
		"Kuwait",
		"Kyrgyzstan",
		"Laos",
		"Latvia",
		"Lebanon",
		"Lesotho",
		"Liberia",
		"Libya",
		"Liechtenstein",
		"Lithuania",
		"Luxembourg",
		"Macedonia",
		"Madagascar",
		"Malawi",
		"Malaysia",
		"Maldives",
		"Mali",
		"Malta",
		"Marshall Islands",
		"Mauritania",
		"Mauritius",
		"Mexico",
		"Micronesia",
		"Moldova",
		"Monaco",
		"Mongolia",
		"Morocco",
		"Mozambique",
		"Myanmar",
		"Namibia",
		"Nauru",
		"Nepa",
		"Netherlands",
		"New Zealand",
		"Nicaragua",
		"Niger",
		"Nigeria",
		"Norway",
		"Oman",
		"Pakistan",
		"Palau",
		"Panama",
		"Papua New Guinea",
		"Paraguay",
		"Peru",
		"Philippines",
		"Poland",
		"Portugal",
		"Qatar",
		"Romania",
		"Russia",
		"Rwanda",
		"Saint Kitts and Nevis",
		"Saint Lucia",
		"Saint Vincent",
		"Samoa",
		"San Marino",
		"Sao Tome and Principe",
		"Saudi Arabia",
		"Senegal",
		"Serbia and Montenegro",
		"Seychelles",
		"Sierra Leone",
		"Singapore",
		"Slovakia",
		"Slovenia",
		"Solomon Islands",
		"Somalia",
		"South Africa",
		"Spain",
		"Sri Lanka",
		"Sudan",
		"Suriname",
		"Swaziland",
		"Sweden",
		"Switzerland",
		"Syria",
		"Taiwan",
		"Tajikistan",
		"Tanzania",
		"Thailand",
		"Togo",
		"Tonga",
		"Trinidad and Tobago",
		"Tunisia",
		"Turkey",
		"Turkmenistan",
		"Tuvalu",
		"Uganda",
		"Ukraine",
		"United Arab Emirates",
		"United Kingdom",
		"United States",
		"Uruguay",
		"Uzbekistan",
		"Vanuatu",
		"Vatican City",
		"Venezuela",
		"Vietnam",
		"Yemen",
		"Zambia",
		"Zimbabwe"
	);
	
	
$bank_list = array("PUNJAB NATIONAL BANK",
	"HDFC BANK",
	"AXIS BANK",
	"CASH",
	"BANK OF BARODA",
	"STATE BANK OF INDIA  ",
	"KASHI GOMTI SAMUT GRAMIN BANK",
	"DENA BANK ",
	"ANDHRA BANK",
	"SOUTH INDIAN BANK",
	"THE BANK OF RAJASTHAN",
	"PUNB NATIONAL BANK ",
	"DENA BANK ",
	"ANDHRA BANK ",
	"BANK OF CEYLON",
	"BANK OF TOKYO-MITSUBISHI UFJ",
	"CANARA BANK",
	"CITIZENCREDIT CO-OPERATIVE BANK",
	"DOMBIVLI NAGARI SAHAKARI BANK",
	"ICICI BANK",
	"ING VYSYA BANK",
	"KARNATAKA BANK",
	"MAHARASHTRA STATE CO OPERATIVE BANK",
	"NUTAN NAGARIK SAHAKARI BANK",
	"PUNJAB AND SIND BANK",
	"SOCIETE GENERALE",
	"SYNDICATE BANK",
	"UCO BANK",
	"ABN AMRO BANK",
	"BANK OF INDIA",
	"BARCLAYS BANK",
	"CATHOLIC SYRIAN BANK",
	"CITY UNION BANK",
	"DEUTSCHE BANK",
	"FEDERAL BANK",
	"IDBI BANK",
	"JAMMU &amp; KASHMIR BANK",
	"KARUR VYSYA BANK",
	"MIZUHO CORPORATE BANK ",
	"OMAN INTERNATIONAL BANK",
	"TAMILNAD MERCANTILE BANK",
	"UNION BANK OF INDIA",
	"ABU DHABI COMMERCIAL BANK",
	"BANK OF AMERICA",
	"BANK OF MAHARASHTRA",
	"BHARAT CO-OPERATIVE BANK (MUMBAI)",
	"CENTRAL BANK OF INDIA",
	"CORPORATION BANK",
	"DEVELOPMENT CREDIT BANK",
	"GREATER BOMBAY COOP BANK",
	"INDIAN BANK",
	"JANAKALYAN SAHAKARI BANK",
	"KOTAK MAHINDRA BANK",
	"NAINITAL BANK",
	"ORIENTAL BANK OF COMMERCE",
	"RATNAKAR BANK",
	"STANDARD CHARTERED BANK",
	"STATE BANK OF MYSORE",
	"TAMILNADU STATE APEX COOP BANK ",
	"UNITED BANK OF INDIA",
	"AHMEDABAD MERCANTILE COOP BANK",
	"BANK OF BAHRAIN AND KUWAIT",
	"BANK OF NOVA SCOTIA",
	"BNP PARIBAS",
	"CHINATRUST COMMERCIAL BANK",
	"COSMOS CO-OPERATIVE BANK",
	"DHANALAKSHMI BANK",
	"INDIAN OVERSEAS BANK",
	"JPMORGAN CHASE BANK, N.A.",
	"LAKSHMI VILAS BANK",
	"NEW INDIA CO-OPERATIVE BANK",
	"PARSIK JANATA SAHAKARI BANK",
	"SARASWAT CO-OPERATIVE BANK",
	"SARASWAT CO-OPERATIVE BANK",
	"STATE BANK OF BIKANER AND JAIPUR",
	"STATE BANK OF PATIALA",
	"THANE JANATA SAHAKARI BANK",
	"VIJAYA BANK",
	"ALLAHABAD BANK",
	"BANK OF RAJASTHAN",
	"CALYON BANK",
	"CITIBANK",
	"DBS BANK",
	"DICGC",
	"HSBC",
	"INDUSIND BANK",
	"KALYAN JANATA SAHARI BANK",
	"MAHANAGAR CO-OP BANK",
	"NKGSB CO-OP BANK",
	"PUNJAB AND MAHARASHTRA CO-OP BANK",
	"SHINHAN BANK",
	"STATE BANK OF HYDERABAD",
	"STATE BANK OF TRAVANCORE",
	"THE SHAMRAO VITHAL CO-OPERATIVE BANK LIMITED",
	"YES BANK",
	"BARCLAYS BANK",
	"OTHERS",				
	"ABHYUDAYA CO-OPERATIVE BANK LIMITED");

$state_list = array("ANDAMAN &amp; NICOBAR IS",
	"ANDHRA PRADESH",
	"ARUNACHAL PRADESH",
	"ASSAM",
	"BIHAR",
	"CHANDIGARH",
	"CHHATTISH GARH",
	"DADRA &amp; NAGAR HAVELI",
	"DAMAN &amp; DIU",
	"DELHI",
	"GOA",
	"GUJRAT",
	"HARYANA",
	"HIMACHAL PRADESH",
	"JAMMU &amp; KASHMIR",
	"JHARKHAND",
	"KARNATAKA",
	"KERALA",
	"LAKSHADWEEP",
	"MADHYA PRADESH",
	"MAHARASHTRA",
	"MANIPUR",
	"MEGHALAYA",
	"MIZORAM",
	"NAGALAND",
	"ORISSA",
	"PONDICHERRY",
	"PUNJAB ",
	"RAJASTHAN",
	"SIKKIM",
	"TAMIL NADU",
	"TRIPURA",
	"UTTAR PRADESH",
	"UTTARAKHAND",
	"WEST BANGAL");
?>	
